# data
data_dir: data/sim
data_name: sim
min_vocab_freq: 1
max_seq_length: 500

# train
shuffle: False
seed: 1337
epochs: 10 #50
batch_size: 23149
optimizer: adam
learning_rate: 0.0005099137446356937
weight_decay: 0
patience: 5

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: KimCNN2Tower
num_filter_per_size: 128 # filter channels
filter_sizes: [2, 4, 8]
dropout: 0.0

# pretrained vocab / embeddings
embed_file: glove.6B.300d
